
- name: Setup DevOps Environment
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Check Docker
      shell: docker --version
      register: docker_output
      ignore_errors: yes

    - name: Show Docker version
      debug:
        var: docker_output.stdout

    - name: Start Minikube
      shell: minikube start
      ignore_errors: yes
