apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-tracker-deployment
  labels:
    app: assignment-tracker

spec:
  replicas: 2

  selector:
    matchLabels:
      app: assignment-tracker

  template:
    metadata:
      labels:
        app: assignment-tracker

    spec:
      containers:
        - name: assignment-tracker
          image: student-assignment-tracker:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:
            - name: FLASK_ENV
              value: "production"

          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5