apiVersion: v1
kind: Service
metadata:
  name: assignment-tracker-service
spec:
  type: NodePort
  selector:
    app: assignment-tracker
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
